<h1 style="color:#c4960c">Minor Packages and Classes Lesson</h1>
<h3>NumPy, DateTime and Statistics</h3>
<hr>

<h4 style="color:#c4960c">Imports</h4>

In [659]:
import numpy as np
import math
import functools
import statistics as stats
import datetime as dt

<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>The Math Package has all the basic matimatical functions that you would expect such as:
    <li>tan</li>
    <li>cos</li>
    <li>sin</li>
    <li>...</li> 
</p>

In [660]:
var1 = math.tan(12)
var1

-0.6358599286615808

In [661]:
var2 = math.cos(12)
var2

0.8438539587324921

In [662]:
var3 = math.sin(12)
var3

-0.5365729180004349

<br><br>
<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>Numpy has advanced mathamatics that expands upon the math package including but far from limited to:
    <li>sum</li>
    <li>min</li>
    <li>max</li>
    <li>count_nonzero</li>
    <li>mean</li>
    <li>...</li>
</p>

<h5>List of Random Numbers</h5>

In [663]:
import random

my_list1 = []
myRand1 = random.randint(10,99)
for x in range(myRand1):
    my_list1.append(random.randint(10,99))
    
my_list2 = []
for x in range(myRand1):
    my_list1.append(random.randint(10,99))

In [664]:
my_dict1 = {
    "Sum": np.sum(my_list1),
    "Min": np.min(my_list1),
    "Max": np.max(my_list1),
    "Count": np.count_nonzero(my_list1)
}
my_dict1

{'Sum': 8314, 'Min': 10, 'Max': 99, 'Count': 162}

<h5>np.dstack()</h5>

In [665]:
myarray1 = np.dstack((my_list1, my_list1))
myarray1[:,0:5]

array([[[17, 17],
        [20, 20],
        [24, 24],
        [79, 79],
        [34, 34]]])

<h5>np.hstack()</h5>

In [666]:
myarray2 = np.hstack((my_list1, my_list1))
myarray2[1:10]

array([20, 24, 79, 34, 66, 91, 60, 32, 66])

<h5>np.vstack()</h5>

In [667]:
myarray3 = np.vstack((my_list1, my_list1))
myarray3[:,0:5]

array([[17, 20, 24, 79, 34],
       [17, 20, 24, 79, 34]])

<h5>np.concatenate()</h5>

In [668]:
myarray4 = np.concatenate((my_list1, my_list1))
myarray4[0:5]

array([17, 20, 24, 79, 34])

<h5>np.stack()</h5>

In [669]:
myarray5 = np.stack((my_list1, my_list1))
myarray5[:,0:5]

array([[17, 20, 24, 79, 34],
       [17, 20, 24, 79, 34]])

<br><br>
<h4 style="color:#c4960c">DateTime</h4>
<hr>
<p>DateTime has most things you will ever need relating to dates and time:
    <li>Date</li>
    <li>DateTime</li>
    <li>Now</li>
    <li>Weekday</li>
    <li>Day</li>
    <li>Month</li>
    <li>Year</li>
    <li>...</li>
</p>

<h5>now()</h5>

In [670]:
myDateTime1 = dt.datetime.now(tz=None)
myDateTime1

datetime.datetime(2020, 5, 7, 15, 7, 11, 234295)

<h5>today()</h5>

In [671]:
myDate1 = dt.date.today()
myDate1

datetime.date(2020, 5, 7)

<h5>day</h5>

In [672]:
myDay1 = dt.date(2020,1,1).day
myDay1

1

<h5>weekday()</h5>

In [673]:
myDay2 = dt.date(2020,1,1).weekday()
myDay2

2

<h5>month</h5>

In [674]:
myMonth1 = dt.date(2020,1,1).month
myMonth1

1

<h5>year</h5>

In [675]:
myYear1 = dt.date(2020,1,1).year
myYear1

2020

<h5>ISO Formats</h5>

In [676]:
myDate2 = dt.date.fromisoformat('2011-11-04')
myDate2

datetime.date(2011, 11, 4)

In [677]:
myDateTime2 = dt.datetime.fromisoformat('2011-11-04T00:05:23')
myDateTime2

datetime.datetime(2011, 11, 4, 0, 5, 23)

<br><br>
<h4 style="color:#c4960c">Statistics</h4>
<hr>
<p>The Statistics package holds everythin you eed to run data analysis over your datasets:
    <li>NormalDist (Normal Distrubtion)</li>
    <li>stdev (Standard Distrubtion)</li>
    <li>pvariance</li>
    <li>median</li>
    <li>multimode</li>
    <li>...</li>
</p>

<br>
<h4>Importing Dataset</h4>

In [678]:
import pandas as pd
df = pd.read_csv(r'http://bit.ly/2cLzoxH', header=0)
df .head()

country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

<h5>Different statistical Tests</h5>

<h5>NormalDist.from_samples()</h5>

In [679]:
my_stat1 =stats.NormalDist.from_samples(df['lifeExp'])
my_stat1

NormalDist(mu=59.47443936619718, sigma=12.917107415241192)

<h5>stdev()</h5>

In [680]:
my_stat2 =stats.stdev(df['lifeExp'])
my_stat2

12.917107415241192

<h5>pvariance()</h5>

In [681]:
my_stat3 =stats.pvariance(df['lifeExp'])
my_stat3

166.75374633370006

<h5>multimode()</h5>

In [682]:
my_stat4 =stats.multimode(df['lifeExp'])
my_stat4

[69.39]

<h5>median_low()</h5>

In [683]:
my_stat5 =stats.median_low(df['lifeExp'])
my_stat5

60.66

<h5>multimode()</h5>

In [684]:
my_stat6 =stats.multimode(df['lifeExp'])
my_stat6

[69.39]

<h5>median_high()</h5>

In [685]:
my_stat7 =stats.median_high(df['lifeExp'])
my_stat7

60.765

<h5>harmonic_mean()</h5>

In [686]:
my_stat8 =stats.harmonic_mean(df['lifeExp'])
my_stat8

56.36126067175875

<h5>geometric_mean()</h5>

In [687]:
my_stat9 =stats.geometric_mean(df['lifeExp'])
my_stat9

57.96498331944521

<h5>fmean()</h5>

In [688]:
my_stat10 =stats.fmean(df['lifeExp'])
my_stat10

59.47443936619718

<h5>mean()</h5>

In [689]:
my_stat11 =stats.mean(df['lifeExp'])
my_stat11

59.47443936619718

<h5>variance()</h5>

In [690]:
my_stat12 =stats.variance(df['lifeExp'])
my_stat12

166.851663976879

<h5>quantiles()</h5>

In [691]:
my_stat13 =stats.quantiles(df['lifeExp'])
my_stat13

[48.172000000000004, 60.7125, 70.84649999999999]

<h5>median_grouped()</h5>

In [692]:
my_stat14 =stats.median_grouped(df['lifeExp'])
my_stat14

60.265

<br><br>
<h2 style="color:#c4960c">Function</h2>
<hr>
<h5>Excel date (stored as a string) to datetime.date</h5>

In [693]:
def str_to_xls_dte(x, opt=1):
    """
    This function converts the Australian date format commonly used in 
    Microsoft Excel into datetime.date format and data type.
    
    Supports the following formats:
    opt 1:  d/m/yyyy or dd/mm/yyyy (default)
    opt 2:  d/m/yy   or d/m/yy
    
    OPTIONAL SECOND ARGUMENT
    in:  date = "01/02/2002"
    in:  print(str_to_els_dte(date))
    out: 2002-02-01
    
    SECOND ARGUMNT PROVIDED
    OPTION 1
    in:  date = "01/02/2002"
    in:  print(str_to_xls_dte(date,1))
    out: 2002-02-01
    
    OPTION 2
    in:  date = "01/02/02"
    in:  print(str_to_xls_dte(date,2))
    out: 2002-02-01
    
    RETURN CLASS
    <class 'datetime.date'>
    format individual: 2002-02-01
    format list:       datetime.date(2020, 2, 1)
    
    REQUIREMENTS
    Packages:
        datetime
    """
    
    try:
        import datetime
        if opt == 1:
            lst = x.split("/")
            d = int(lst[0])
            m = int(lst[1])
            y = int(lst[2])
            return datetime.date(y,m,d)

        if opt == 2:
            lst = x.split("/")
            d = int(lst[0])
            m = int(lst[1])
            y = int(str(20) + lst[2])
            return datetime.date(y,m,d)
    except ValueError as err:
        raise
            

In [694]:
help(str_to_xls_dte)

Help on function str_to_xls_dte in module __main__:

str_to_xls_dte(x, opt=1)
    This function converts the Australian date format commonly used in 
    Microsoft Excel into datetime.date format and data type.
    
    Supports the following formats:
    opt 1:  d/m/yyyy or dd/mm/yyyy (default)
    opt 2:  d/m/yy   or d/m/yy
    
    OPTIONAL SECOND ARGUMENT
    in:  date = "01/02/2002"
    in:  print(str_to_els_dte(date))
    out: 2002-02-01
    
    SECOND ARGUMNT PROVIDED
    OPTION 1
    in:  date = "01/02/2002"
    in:  print(str_to_xls_dte(date,1))
    out: 2002-02-01
    
    OPTION 2
    in:  date = "01/02/02"
    in:  print(str_to_xls_dte(date,2))
    out: 2002-02-01
    
    RETURN CLASS
    <class 'datetime.date'>
    format individual: 2002-02-01
    format list:       datetime.date(2020, 2, 1)
    
    REQUIREMENTS
    Packages:
        datetime



In [695]:
myXlsDate1 = "01/02/2002"

print("Without opt:")
print(str_to_xls_dte(myXlsDate1))
print("-------------------")

print("With opt 1:")
print(str_to_xls_dte(myXlsDate1,1))
print("-------------------")

print("With opt 2:")
myXlsDate2 = "01/02/02"
print(type(str_to_xls_dte(myXlsDate2,2)))
print("-------------------")

Without opt:
2002-02-01
-------------------
With opt 1:
2002-02-01
-------------------
With opt 2:
<class 'datetime.date'>
-------------------


In [696]:
lstXlsDates1 = ['1/2/20', '2/2/20', '3/2/20', '4/2/20']

lstXlsDates1 = list(
    map(
        lambda x: str_to_xls_dte(x,2),
        lstXlsDates1
    )
)

lstXlsDates1[0]

datetime.date(2020, 2, 1)

<br><br>
<h2 style="color:#c4960c">Classes</h2>
<hr>
<p>A class can be utilised for a vatiaty of purposes:
    <li>Store and orginise Functions</li>
    <li>Store objects to run functions on</li>
    <li>Initiation of steps required to be taken before one or more functions are enacted</li>
    <li>Run subsequent steps such as logging</li>
</p>

In [697]:
class Xls_DateTime:
    """
    Help text goes here
    
    """
    import datetime
    
    
    
    
    #This function in run at everytime the class is called
    #It defigns your variables to be used in class functions
    def __init__(self, dte, opt= 1):
        """
        Help text goes here
        """
        self.dte = dte
        self.opt = opt
        self.lst = dte.split("/")
        self.d = int(self.lst[0])
        self.m = int(self.lst[1])
        self.y = int(self.lst[2])
        self.my = int(str(20) + self.lst[2])
        

        
        
    #Function One
    
    def xls_date_to_date(self):
        """
        Help text goes here
        """
        if self.opt == 1:
            return datetime.date(self.y, self.m, self.d)

        if self.opt == 2:
            return datetime.date(self.my, self.m, self.d)
        
        
        
    #Function Two  
    def xls_date_to_datetime(self, h=0, m=0, s=0):
        """
        Help text goes here
        """
        if self.opt == 1:
            return datetime.datetime(self.y, self.m, self.d, h,m,s)

        if self.opt == 2:
            return datetime.datetime(self.my, self.m, self.d, h,m,s )
    
        


<h3 style="color:#c4960c">Class Objects</h3>

<h5>Set Date Variable</h5>

In [698]:
myXlsDate1 = "01/02/2002"

<br><br><br>
<hr>
<h4>Create a class object</h4>
<hr>

In [699]:
My_Date1 = Xls_DateTime(myXlsDate1, 1)            #Creating a class object

<br>
<h5>Print a class object</h5>

In [700]:
print("First Class Object")
print("xls date:", My_Date1.dte)                  #Print class.dte                         
print("Option:", My_Date1.opt)                    #Print class.opt

First Class Object
xls date: 01/02/2002
Option: 1


<br>
<h5>Run class.function( ) on object</h5>

In [701]:
print(My_Date1.xls_date_to_date())                #Run class.function

2002-02-01


<br><br><br><br>
<hr>
<h4>Create a class object</h4>
<hr>

In [702]:
My_Date2 = Xls_DateTime("01/02/2002")             #Creating a class object (opt = 1 is default)

<br>
<h5>Print a class object</h5>

In [703]:
print("Second Class Object")

print("xls date:", My_Date2.dte)                  #Print class.dte              
print("Option:", My_Date2.opt)                    #Run class.function

Second Class Object
xls date: 01/02/2002
Option: 1


<br>
<h5>Run class.function( ) on object</h5>

In [704]:
print(My_Date2.xls_date_to_date())                #Run class.function

2002-02-01


<br><br><br><br>
<hr>
<h4>Create a class object</h4>
<hr>


In [705]:
My_Date3 = Xls_DateTime("01/02/02", 2)            #Creating a class object

<br>
<h5>Print a class object</h5>

In [706]:
print("Second Class Object")

print("xls date:", My_Date3.dte)                  #Print class.dte      
print("Option:", My_Date3.opt)                    #Print class.opt

Second Class Object
xls date: 01/02/02
Option: 2


<br>
<h5>Run class.function( ) on object</h5>

In [707]:
print(My_Date3.xls_date_to_date())                #Run class.function

2002-02-01




<br><br><br><br>
<hr>
<h4>Call a class.function( ) without making a class object</h4>
<hr>

In [708]:
Xls_DateTime(myXlsDate1, 1).xls_date_to_date()

datetime.date(2002, 2, 1)

<br><br><br><br>
<h3 style="color:#c4960c">Reuse class objects accross multiple class.functions</h3>

<h4>Create Variable</h4>

In [709]:
myXlsDate2 = "01/02/2019"

<br><br>
<h4>Create class object</h4>

In [714]:
My_Date4 = Xls_DateTime(myXlsDate2, 1)             #Creating a class object
My_Date4

<br><br>
<h4>Print class object</h4>

In [711]:
print("Class Objects:")
print("xls date:", My_Date4.dte)                   #Print class.dte                         
print("Option:", My_Date4.opt)  

Class Objects:
xls date: 01/02/2019
Option: 1


<br><br>
<h4>Run class.function( ) on class objects</h4>

In [712]:
print("Date Function:")
print(My_Date4.xls_date_to_date())                 #Run class.function

Date Function:
2019-02-01


In [713]:
print("DateTime Function:")
print(My_Date4.xls_date_to_datetime(12,1,30))      #Run class.function

DateTime Function:
2019-02-01 12:01:30
