<h1 style="color:#c4960c">Minor Packages Lesson</h1>
<h3>NumPy, DateTime, Functools and Statistics</h3>
<hr>

<h4 style="color:#c4960c">Imports</h4>

In [241]:
import numpy as np
import math
import functools
import statistics as stats
import datetime as dt

<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>The Math Package has all the basic matimatical functions that you would expect such as:
    <li>tan</li>
    <li>cos</li>
    <li>sin</li>
    <li>...</li> 
</p>

In [216]:
var1 = math.tan(12)
var1

-0.6358599286615808

In [217]:
var2 = math.cos(12)
var2

0.8438539587324921

In [218]:
var3 = math.sin(12)
var3

-0.5365729180004349

<br><br>
<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>Numpy has advanced mathamatics that expands upon the math package including but far from limited to:
    <li>sum</li>
    <li>min</li>
    <li>max</li>
    <li>count_nonzero</li>
    <li>mean</li>
    <li>...</li>
</p>

<h5>List of Random Numbers</h5>

In [242]:
import random

my_list1 = []
myRand1 = random.randint(10,99)
for x in range(myRand1):
    my_list1.append(random.randint(10,99))
    
my_list2 = []
for x in range(myRand1):
    my_list1.append(random.randint(10,99))

In [220]:
my_dict1 = {
    "Sum": np.sum(my_list1),
    "Min": np.min(my_list1),
    "Max": np.max(my_list1),
    "Count": np.count_nonzero(my_list1)
}
my_dict1

{'Sum': 2927, 'Min': 11, 'Max': 96, 'Count': 50}

<h5>np.dstack()</h5>

In [221]:
myarray1 = np.dstack((my_list1, my_list1))
myarray1[:,0:5]

array([[[38, 38],
        [81, 81],
        [93, 93],
        [90, 90],
        [93, 93]]])

<h5>np.hstack()</h5>

In [222]:
myarray2 = np.hstack((my_list1, my_list1))
myarray2[1:10]

array([81, 93, 90, 93, 12, 90, 25, 44, 42])

<h5>np.vstack()</h5>

In [223]:
myarray3 = np.vstack((my_list1, my_list1))
myarray3[:,0:5]

array([[38, 81, 93, 90, 93],
       [38, 81, 93, 90, 93]])

<h5>np.concatenate()</h5>

In [224]:
myarray4 = np.concatenate((my_list1, my_list1))
myarray4[0:5]

array([38, 81, 93, 90, 93])

<h5>np.stack()</h5>

In [225]:
myarray5 = np.stack((my_list1, my_list1))
myarray5[:,0:5]

array([[38, 81, 93, 90, 93],
       [38, 81, 93, 90, 93]])

<br><br>
<h4 style="color:#c4960c">DateTime</h4>
<hr>
<p>DateTime has most things you will ever need relating to dates and time:
    <li>Date</li>
    <li>DateTime</li>
    <li>Now</li>
    <li>Weekday</li>
    <li>Day</li>
    <li>Month</li>
    <li>Year</li>
    <li>...</li>
</p>

<h5>now()</h5>

In [226]:
myDateTime1 = dt.datetime.now(tz=None)
myDateTime1

datetime.datetime(2020, 5, 6, 15, 50, 3, 277809)

<h5>today()</h5>

In [227]:
myDate1 = dt.date.today()
myDate1

datetime.date(2020, 5, 6)

<h5>day</h5>

In [228]:
myDay1 = dt.date(2020,1,1).day
myDay1

1

<h5>weekday()</h5>

In [229]:
myDay2 = dt.date(2020,1,1).weekday()
myDay2

2

<h5>month</h5>

In [230]:
myMonth1 = dt.date(2020,1,1).month
myMonth1

1

<h5>year</h5>

In [231]:
myYear1 = dt.date(2020,1,1).year
myYear1

2020

<h5>ISO Formats</h5>

In [232]:
myDate2 = dt.date.fromisoformat('2011-11-04')
myDate2

datetime.date(2011, 11, 4)

In [233]:
myDateTime2 = dt.datetime.fromisoformat('2011-11-04T00:05:23')
myDateTime2

datetime.datetime(2011, 11, 4, 0, 5, 23)

<br><br>
<h4 style="color:#c4960c">Statistics</h4>
<hr>
<p>The Statistics package holds everythin you eed to run data analysis over your datasets:
    <li>NormalDist (Normal Distrubtion)</li>
    <li>stdev (Standard Distrubtion)</li>
    <li>pvariance</li>
    <li>median</li>
    <li>multimode</li>
    <li>...</li>
</p>

<br>
<h4>Importing Dataset</h4>

In [234]:
import pandas as pd
df = pd.read_csv(r'http://bit.ly/2cLzoxH', header=0)
df .head()

country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

<h5>Different statistical Tests</h5>

<h5>NormalDist.from_samples()</h5>

In [235]:
my_stat1 =stats.NormalDist.from_samples(df['lifeExp'])
my_stat1

NormalDist(mu=59.47443936619718, sigma=12.917107415241192)

<h5>stdev<()/h5>

In [236]:
my_stat2 =stats.stdev(df['lifeExp'])
my_stat2

12.917107415241192

<h5>pvariance()</h5>

In [237]:
my_stat3 =stats.pvariance(df['lifeExp'])
my_stat3

166.75374633370006

<h5>multimode()</h5>

In [238]:
my_stat4 =stats.multimode(df['lifeExp'])
my_stat4

[69.39]

<h5>median_low()</h5>

In [239]:
my_stat5 =stats.median_low(df['lifeExp'])
my_stat5

60.66

<h5>multimode()</h5>

In [ ]:
my_stat6 =stats.multimode(df['lifeExp'])
my_stat6

<h5>median_high()</h5>

In [ ]:
my_stat7 =stats.median_high(df['lifeExp'])
my_stat7

<h5>harmonic_mean()</h5>

In [ ]:
my_stat8 =stats.harmonic_mean(df['lifeExp'])
my_stat8

<h5>geometric_mean()</h5>

In [ ]:
my_stat9 =stats.geometric_mean(df['lifeExp'])
my_stat9

<h5>fmean()</h5>

In [ ]:
my_stat10 =stats.fmean(df['lifeExp'])
my_stat10

<h5>mean()</h5>

In [ ]:
my_stat11 =stats.mean(df['lifeExp'])
my_stat11

<h5>variance()</h5>

In [ ]:
my_stat12 =stats.variance(df['lifeExp'])
my_stat12

<h5>quantiles()</h5>

In [ ]:
my_stat13 =stats.quantiles(df['lifeExp'])
my_stat13

<h5>median_grouped()</h5>

In [243]:
my_stat14 =stats.median_grouped(df['lifeExp'])
my_stat14

60.265

<h4 style="color:#c4960c">Functools</h4>
<hr>
<p>The Functools Package has ....:
    <li>...</li>
    <li>...</li>
    <li>...</li>
    <li>...</li> 
</p>