<h1 style="color:#c4960c">Minor Packages Lesson</h1>
<h3>NumPy, DateTime and Statistics</h3>
<hr>

<h4 style="color:#c4960c">Imports</h4>

In [1]:
import numpy as np
import math
import functools
import statistics as stats
import datetime as dt

<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>The Math Package has all the basic matimatical functions that you would expect such as:
    <li>tan</li>
    <li>cos</li>
    <li>sin</li>
    <li>...</li> 
</p>

In [2]:
var1 = math.tan(12)
var1

-0.6358599286615808

In [3]:
var2 = math.cos(12)
var2

0.8438539587324921

In [4]:
var3 = math.sin(12)
var3

-0.5365729180004349

<br><br>
<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>Numpy has advanced mathamatics that expands upon the math package including but far from limited to:
    <li>sum</li>
    <li>min</li>
    <li>max</li>
    <li>count_nonzero</li>
    <li>mean</li>
    <li>...</li>
</p>

<h5>List of Random Numbers</h5>

In [5]:
import random

my_list1 = []
myRand1 = random.randint(10,99)
for x in range(myRand1):
    my_list1.append(random.randint(10,99))
    
my_list2 = []
for x in range(myRand1):
    my_list1.append(random.randint(10,99))

In [6]:
my_dict1 = {
    "Sum": np.sum(my_list1),
    "Min": np.min(my_list1),
    "Max": np.max(my_list1),
    "Count": np.count_nonzero(my_list1)
}
my_dict1

{'Sum': 9101, 'Min': 10, 'Max': 98, 'Count': 158}

<h5>np.dstack()</h5>

In [7]:
myarray1 = np.dstack((my_list1, my_list1))
myarray1[:,0:5]

array([[[26, 26],
        [13, 13],
        [66, 66],
        [29, 29],
        [24, 24]]])

<h5>np.hstack()</h5>

In [8]:
myarray2 = np.hstack((my_list1, my_list1))
myarray2[1:10]

array([13, 66, 29, 24, 98, 53, 65, 39, 76])

<h5>np.vstack()</h5>

In [9]:
myarray3 = np.vstack((my_list1, my_list1))
myarray3[:,0:5]

array([[26, 13, 66, 29, 24],
       [26, 13, 66, 29, 24]])

<h5>np.concatenate()</h5>

In [10]:
myarray4 = np.concatenate((my_list1, my_list1))
myarray4[0:5]

array([26, 13, 66, 29, 24])

<h5>np.stack()</h5>

In [11]:
myarray5 = np.stack((my_list1, my_list1))
myarray5[:,0:5]

array([[26, 13, 66, 29, 24],
       [26, 13, 66, 29, 24]])

<br><br>
<h4 style="color:#c4960c">DateTime</h4>
<hr>
<p>DateTime has most things you will ever need relating to dates and time:
    <li>Date</li>
    <li>DateTime</li>
    <li>Now</li>
    <li>Weekday</li>
    <li>Day</li>
    <li>Month</li>
    <li>Year</li>
    <li>...</li>
</p>

<h5>now()</h5>

In [12]:
myDateTime1 = dt.datetime.now(tz=None)
myDateTime1

datetime.datetime(2020, 5, 7, 8, 34, 20, 868508)

<h5>today()</h5>

In [13]:
myDate1 = dt.date.today()
myDate1

datetime.date(2020, 5, 7)

<h5>day</h5>

In [14]:
myDay1 = dt.date(2020,1,1).day
myDay1

1

<h5>weekday()</h5>

In [15]:
myDay2 = dt.date(2020,1,1).weekday()
myDay2

2

<h5>month</h5>

In [16]:
myMonth1 = dt.date(2020,1,1).month
myMonth1

1

<h5>year</h5>

In [17]:
myYear1 = dt.date(2020,1,1).year
myYear1

2020

<h5>ISO Formats</h5>

In [18]:
myDate2 = dt.date.fromisoformat('2011-11-04')
myDate2

datetime.date(2011, 11, 4)

In [19]:
myDateTime2 = dt.datetime.fromisoformat('2011-11-04T00:05:23')
myDateTime2

datetime.datetime(2011, 11, 4, 0, 5, 23)

<br><br>
<h4 style="color:#c4960c">Statistics</h4>
<hr>
<p>The Statistics package holds everythin you eed to run data analysis over your datasets:
    <li>NormalDist (Normal Distrubtion)</li>
    <li>stdev (Standard Distrubtion)</li>
    <li>pvariance</li>
    <li>median</li>
    <li>multimode</li>
    <li>...</li>
</p>

<br>
<h4>Importing Dataset</h4>

In [20]:
import pandas as pd
df = pd.read_csv(r'http://bit.ly/2cLzoxH', header=0)
df .head()

country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

<h5>Different statistical Tests</h5>

<h5>NormalDist.from_samples()</h5>

In [21]:
my_stat1 =stats.NormalDist.from_samples(df['lifeExp'])
my_stat1

NormalDist(mu=59.47443936619718, sigma=12.917107415241192)

<h5>stdev()</h5>

In [22]:
my_stat2 =stats.stdev(df['lifeExp'])
my_stat2

12.917107415241192

<h5>pvariance()</h5>

In [23]:
my_stat3 =stats.pvariance(df['lifeExp'])
my_stat3

166.75374633370006

<h5>multimode()</h5>

In [24]:
my_stat4 =stats.multimode(df['lifeExp'])
my_stat4

[69.39]

<h5>median_low()</h5>

In [25]:
my_stat5 =stats.median_low(df['lifeExp'])
my_stat5

60.66

<h5>multimode()</h5>

In [26]:
my_stat6 =stats.multimode(df['lifeExp'])
my_stat6

[69.39]

<h5>median_high()</h5>

In [27]:
my_stat7 =stats.median_high(df['lifeExp'])
my_stat7

60.765

<h5>harmonic_mean()</h5>

In [28]:
my_stat8 =stats.harmonic_mean(df['lifeExp'])
my_stat8

56.36126067175875

<h5>geometric_mean()</h5>

In [29]:
my_stat9 =stats.geometric_mean(df['lifeExp'])
my_stat9

57.96498331944521

<h5>fmean()</h5>

In [30]:
my_stat10 =stats.fmean(df['lifeExp'])
my_stat10

59.47443936619718

<h5>mean()</h5>

In [31]:
my_stat11 =stats.mean(df['lifeExp'])
my_stat11

59.47443936619718

<h5>variance()</h5>

In [32]:
my_stat12 =stats.variance(df['lifeExp'])
my_stat12

166.851663976879

<h5>quantiles()</h5>

In [33]:
my_stat13 =stats.quantiles(df['lifeExp'])
my_stat13

[48.172000000000004, 60.7125, 70.84649999999999]

<h5>median_grouped()</h5>

In [34]:
my_stat14 =stats.median_grouped(df['lifeExp'])
my_stat14

60.265

<br><br>
<h4 style="color:#c4960c">Function Practice</h4>
<hr>
<h5>Excel date (stored as a string) to datetime.date</h5>

In [269]:
def str_to_xls_dte(x, opt=1):
    """
    This function converts the Australian date format commonly used in 
    Microsoft Excel into datetime.date format and data type.
    
    Supports the following formats:
    opt 1:  d/m/yyyy or dd/mm/yyyy (default)
    opt 2:  d/m/yy   or d/m/yy
    
    OPTIONAL SECOND ARGUMENT
    in:  date = "01/02/2002"
    in:  print(str_to_els_dte(date))
    out: 2002-02-01
    
    SECOND ARGUMNT PROVIDED
    OPTION 1
    in:  date = "01/02/2002"
    in:  print(str_to_xls_dte(date,1))
    out: 2002-02-01
    
    OPTION 2
    in:  date = "01/02/02"
    in:  print(str_to_xls_dte(date,2))
    out: 2002-02-01
    
    RETURN CLASS
    <class 'datetime.date'>
    format individual: 2002-02-01
    format list:       datetime.date(2020, 2, 1)
    
    REQUIREMENTS
    Packages:
        datetime
    """
    
    try:
        import datetime
        if opt == 1:
            lst = x.split("/")
            d = int(lst[0])
            m = int(lst[1])
            y = int(lst[2])
            return datetime.date(y,m,d)

        if opt == 2:
            lst = x.split("/")
            d = int(lst[0])
            m = int(lst[1])
            y = int(str(20) + lst[2])
            return datetime.date(y,m,d)
    except ValueError as err:
        raise
            

In [270]:
help(str_to_xls_dte)

Help on function str_to_xls_dte in module __main__:

str_to_xls_dte(x, opt=1)
    This function converts the Australian date format commonly used in 
    Microsoft Excel into datetime.date format and data type.
    
    Supports the following formats:
    opt 1:  d/m/yyyy or dd/mm/yyyy (default)
    opt 2:  d/m/yy   or d/m/yy
    
    OPTIONAL SECOND ARGUMENT
    in:  date = "01/02/2002"
    in:  print(str_to_els_dte(date))
    out: 2002-02-01
    
    SECOND ARGUMNT PROVIDED
    OPTION 1
    in:  date = "01/02/2002"
    in:  print(str_to_xls_dte(date,1))
    out: 2002-02-01
    
    OPTION 2
    in:  date = "01/02/02"
    in:  print(str_to_xls_dte(date,2))
    out: 2002-02-01
    
    RETURN CLASS
    <class 'datetime.date'>
    format: 2002-02-01
    
    REQUIREMENTS
    Packages:
        datetime



In [260]:
myXlsDate1 = "01/02/2002"
myXlsDate2 = "01/02/02"
print(str_to_xls_dte(myXlsDate1))
print(str_to_xls_dte(myXlsDate1,1))
print(type(str_to_xls_dte(myXlsDate2,2)))

2002-02-01
2002-02-01
<class 'datetime.date'>


In [273]:
lstXlsDates1 = ['1/2/20', '2/2/20', '3/2/20', '4/2/20']

lstXlsDates1 = list(
    map(
        lambda x: str_to_xls_dte(x,2),
        lstXlsDates1
    )
)

lstXlsDates1[0]

datetime.date(2020, 2, 1)