<h1 style="color:#c4960c">Minor Packages</h1>
<h3>NumPy, DateTime and Statistics</h3>
<hr>

<h4 style="color:#c4960c">Imports</h4>

In [3]:
import numpy as np
import math
import functools
import statistics as stats
import datetime as dt

<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>The Math Package has all the basic matimatical functions that you would expect such as:
    <li>tan</li>
    <li>cos</li>
    <li>sin</li>
    <li>...</li> 
</p>

In [4]:
var1 = math.tan(12)
var1

-0.6358599286615808

In [5]:
var2 = math.cos(12)
var2

0.8438539587324921

In [6]:
var3 = math.sin(12)
var3

-0.5365729180004349

<br><br>
<h4 style="color:#c4960c">Numpy</h4>
<hr>
<p>Numpy has advanced mathamatics that expands upon the math package including but far from limited to:
    <li>sum</li>
    <li>min</li>
    <li>max</li>
    <li>count_nonzero</li>
    <li>mean</li>
    <li>...</li>
</p>

<h5>List of Random Numbers</h5>

In [130]:
import random

my_list1 = []
myRand1 = random.randint(10,99)
for x in range(myRand1):
    my_list1.append(random.randint(10,99))
    
my_list2 = []
for x in range(myRand1):
    my_list2.append(random.randint(10,99))
    
print(my_list1)
print(my_list2)

[66, 51, 57, 37, 18, 86, 84, 32, 17, 30, 19, 38, 62, 51, 90, 18, 53, 11, 63, 25, 24, 43, 19, 90, 24, 43, 98, 31, 77, 41, 35, 86, 92, 79, 52, 29, 18, 85, 99, 54, 74, 47, 89, 40, 92, 49, 44, 48, 69, 63, 62, 33, 11, 54, 54, 91, 80]
[55, 49, 23, 13, 31, 91, 61, 67, 13, 16, 95, 60, 14, 76, 33, 72, 72, 85, 18, 15, 37, 65, 53, 40, 81, 36, 81, 44, 52, 19, 20, 47, 70, 82, 21, 75, 62, 90, 85, 69, 31, 10, 81, 90, 13, 26, 55, 81, 66, 51, 25, 74, 51, 54, 35, 17, 94]


In [124]:
my_dict1 = {
    "Sum": np.sum(my_list1),
    "Min": np.min(my_list1),
    "Max": np.max(my_list1),
    "Count": np.count_nonzero(my_list1)
}
print(my_dict1)
print(my_dict1['Sum'])
print(my_dict1['Min'])
print(my_dict1['Max'])
print(my_dict1['Count'])

{'Sum': 3189, 'Min': 11, 'Max': 98, 'Count': 55}
3189
11
98
55


<h5>np.dstack()</h5>

In [114]:
myarray1 = np.dstack((my_list1, my_list2))
myarray1[:,0:5]

array([[[63, 92],
        [58, 84],
        [67, 39],
        [25, 40],
        [74, 61]]])

<h5>np.hstack()</h5>

In [115]:
myarray2 = np.hstack((my_list1, my_list2))
myarray2[1:10]

array([58, 67, 25, 74, 71, 66, 75, 92, 91])

<h5>np.vstack()</h5>

In [116]:
myarray3 = np.vstack((my_list1, my_list2))
myarray3[:,0:5]

array([[63, 58, 67, 25, 74],
       [92, 84, 39, 40, 61]])

<h5>np.concatenate()</h5>

In [117]:
myarray4 = np.concatenate((my_list1, my_list2))
myarray4[0:5]

array([63, 58, 67, 25, 74])

<h5>np.stack()</h5>

In [118]:
myarray5 = np.stack((my_list1, my_list2))
myarray5[:,0:5]

array([[63, 58, 67, 25, 74],
       [92, 84, 39, 40, 61]])

<br><br>
<h4 style="color:#c4960c">DateTime</h4>
<hr>
<p>DateTime has most things you will ever need relating to dates and time:
    <li>Date</li>
    <li>DateTime</li>
    <li>Now</li>
    <li>Weekday</li>
    <li>Day</li>
    <li>Month</li>
    <li>Year</li>
    <li>...</li>
</p>

<h5>now()</h5>

In [14]:
myDateTime1 = dt.datetime.now(tz=None)
myDateTime1

datetime.datetime(2020, 5, 7, 21, 12, 12, 20316)

<h5>today()</h5>

In [15]:
myDate1 = dt.date.today()
myDate1

datetime.date(2020, 5, 7)

<h5>day</h5>

In [16]:
myDay1 = dt.date(2020,1,1).day
myDay1

1

<h5>weekday()</h5>

In [17]:
myDay2 = dt.date(2020,1,1).weekday()
myDay2

2

<h5>month</h5>

In [18]:
myMonth1 = dt.date(2020,1,1).month
myMonth1

1

<h5>year</h5>

In [19]:
myYear1 = dt.date(2020,1,1).year
myYear1

2020

<h5>ISO Formats</h5>

In [20]:
myDate2 = dt.date.fromisoformat('2011-11-04')
myDate2

datetime.date(2011, 11, 4)

In [21]:
myDateTime2 = dt.datetime.fromisoformat('2011-11-04T00:05:23')
myDateTime2

datetime.datetime(2011, 11, 4, 0, 5, 23)

<br><br>
<h4 style="color:#c4960c">Statistics</h4>
<hr>
<p>The Statistics package holds everythin you eed to run data analysis over your datasets:
    <li>NormalDist (Normal Distrubtion)</li>
    <li>stdev (Standard Distrubtion)</li>
    <li>pvariance</li>
    <li>median</li>
    <li>multimode</li>
    <li>...</li>
</p>

<br>
<h4>Importing Dataset</h4>

In [22]:
import pandas as pd
df = pd.read_csv(r'http://bit.ly/2cLzoxH', header=0)
df .head()

country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

<h5>Different statistical Tests</h5>

<h5>NormalDist.from_samples()</h5>

In [23]:
my_stat1 =stats.NormalDist.from_samples(df['lifeExp'])
my_stat1

NormalDist(mu=59.47443936619718, sigma=12.917107415241192)

<h5>stdev()</h5>

In [24]:
my_stat2 =stats.stdev(df['lifeExp'])
my_stat2

12.917107415241192

<h5>pvariance()</h5>

In [25]:
my_stat3 =stats.pvariance(df['lifeExp'])
my_stat3

166.75374633370006

<h5>multimode()</h5>

In [26]:
my_stat4 =stats.multimode(df['lifeExp'])
my_stat4

[69.39]

<h5>median_low()</h5>

In [27]:
my_stat5 =stats.median_low(df['lifeExp'])
my_stat5

60.66

<h5>multimode()</h5>

In [28]:
my_stat6 =stats.multimode(df['lifeExp'])
my_stat6

[69.39]

<h5>median_high()</h5>

In [29]:
my_stat7 =stats.median_high(df['lifeExp'])
my_stat7

60.765

<h5>harmonic_mean()</h5>

In [30]:
my_stat8 =stats.harmonic_mean(df['lifeExp'])
my_stat8

56.36126067175875

<h5>geometric_mean()</h5>

In [31]:
my_stat9 =stats.geometric_mean(df['lifeExp'])
my_stat9

57.96498331944521

<h5>fmean()</h5>

In [32]:
my_stat10 =stats.fmean(df['lifeExp'])
my_stat10

59.47443936619718

<h5>mean()</h5>

In [33]:
my_stat11 =stats.mean(df['lifeExp'])
my_stat11

59.47443936619718

<h5>variance()</h5>

In [34]:
my_stat12 =stats.variance(df['lifeExp'])
my_stat12

166.851663976879

<h5>quantiles()</h5>

In [35]:
my_stat13 =stats.quantiles(df['lifeExp'])
my_stat13

[48.172000000000004, 60.7125, 70.84649999999999]

<h5>median_grouped()</h5>

In [36]:
my_stat14 =stats.median_grouped(df['lifeExp'])
my_stat14

60.265

<h3>Practice</h3>
<h4>numpy</h4>

In [37]:
list1 = []
myRand2 = random.randint(1,1000)
for x in range(myRand2):
    list1.append(random.randint(1,1000 ))
list2 = []
for x in range(myRand2):
    list2.append(random.randint(1,1000))
list3 = []
for x in range(myRand2):
    list3.append(random.randint(1,1000))
list4 = []
for x in range(myRand2):
    list4.append(random.randint(1,1000))
list5 = []
for x in range(myRand2):
    list5.append(random.randint(1,1000))
list6 = []
for x in range(myRand2):
    list6.append(random.randint(1,1000))
list7 = []
for x in range(myRand2):
    list7.append(random.randint(1,1000))
list8 = []
for x in range(myRand2):
    list8.append(random.randint(1,1000))
list9 = []
for x in range(myRand2):
    list9.append(random.randint(1,1000))
dataset = list(zip(list1, list2, list3, list4, list5, list6, list7, list8, list9))
pd.DataFrame(dataset)

0    1    2    3    4    5    6    7    8
0    369  246  229  743  999  528  993  844  242
1    995  457  669  322  876  432  681  440  297
2    460  637  224  497   38  671  757  766   59
3    815  285  709  501  799  496  476  770  793
4    872  487  980  258  585  258  511  645  455
..   ...  ...  ...  ...  ...  ...  ...  ...  ...
677  909  834  165  413  287  993  521  542  629
678  848  624  284  289  529  991  413  470  862
679  542  984  444  300  810  571  839  691  330
680  350  902  982  465  862  871   31  803  446
681  219  680  351  375  838  138  606  441  533

[682 rows x 9 columns]

In [38]:
np.max(dataset)

1000

In [39]:
np.sum(dataset)

3063881

In [40]:
np.sum(dataset[0])

5193

In [41]:
def bins_dataset(lst):
    gl1_10 = 0
    gl10_100 = 0
    gl100_1000 = 0
    gr1000 = 0
    
    for x in dataset:
        for y in x:
            if y < 10:
                gl1_10 += 1
            elif y < 100 and y > 10:
                gl10_100 += 1
            elif y < 1000 and y > 10:
                gl100_1000 += 1
            else:
                gr1000 += 1
        
    return("less than 10: " + str(gl1_10) + 
           "  -  less than 10 & greater than 100: " + str(gl10_100) + 
           "  -  less than 100 & greater tha 1000:: " + str(gl100_1000) + 
           "  -  greater tha 1000: " + str(gr1000)
          )
    
    
bins_dataset(dataset)

'less than 10: 46  -  less than 10 & greater than 100: 554  -  less than 100 & greater tha 1000:: 5528  -  greater tha 1000: 10'

<h4>statistics</h4>

In [42]:
stats.fsum(dataset[0])

5193.0

In [43]:
stats.mode(dataset[0])

369

<h4>datetime</h4>

In [44]:
dataset2 = [dt.date(2020,1,2), dt.date(2020,1,3),dt.date(2020,1,4),dt.date(2020,1,5)]
dataset2

[datetime.date(2020, 1, 2),
 datetime.date(2020, 1, 3),
 datetime.date(2020, 1, 4),
 datetime.date(2020, 1, 5)]

In [45]:
for x in dataset2:
    print(x.weekday())

3
4
5
6


In [75]:
def weekday_name(date):
    days = [[0, "Sunday"],[2, "Monday"],[3, "Tuesday"],[4, "Wednesday"],[5, "Thrursday"],[6, "Friday"],[7, "Saturday"]]

    for y in days:
        if date.weekday() == y[0]:
            return y[1]

In [76]:
weekday_name(dt.date(2020,1,1))

'Monday'

In [77]:
print(
    list(
        map(
        lambda x: weekday_name(x), dataset2
        )
    )
)

['Tuesday', 'Wednesday', 'Thrursday', 'Friday']


<br><br>
<h1>Chalange</h1>
<p>Turn this into a function</p>

In [88]:
sdate = date(2019, 10, 1)   # start date
edate = date(2019, 10, 5)   # end datedelta = edate - sdate       # as timedelta

dte_lst = []

delta = edate - sdate       # as timedelta

for i in range(delta.days + 1):
    day = sdate + timedelta(days=i)
    dte_lst.append(day)
dte_lst

[datetime.date(2019, 10, 1),
 datetime.date(2019, 10, 2),
 datetime.date(2019, 10, 3),
 datetime.date(2019, 10, 4),
 datetime.date(2019, 10, 5)]

<h1>Chalange</h1>
<p>Create a functio that prints a date in the folowing format:
<li>day name dd mmm yy</li>
 <li>Monday 01 Feb 20</li>
    </p>

<h1>Chalange</h1>
<p>Create a loop to find the mean of each column:
    </p>

In [92]:
c_list1 = []
myRand2 = random.randint(1,1000)
for x in range(10):
    c_list1.append(random.randint(1,1000 ))
c_list2 = []
for x in range(10):
    c_list2.append(random.randint(1,1000))
c_list3 = []
for x in range(10):
    c_list3.append(random.randint(1,1000))


c_lst = list(zip(c_list1, c_list2, c_list3))
c_lst

[(743, 665, 487),
 (682, 160, 797),
 (991, 746, 507),
 (591, 66, 987),
 (453, 226, 921),
 (102, 44, 88),
 (406, 475, 607),
 (435, 616, 90),
 (463, 30, 838),
 (518, 430, 514)]